-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 10:52:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BudgetPlanner
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BudgetPlanner` ;

-- -----------------------------------------------------
-- Schema BudgetPlanner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BudgetPlanner` DEFAULT CHARACTER SET utf8 ;
USE `BudgetPlanner` ;

-- -----------------------------------------------------
-- Table `BudgetPlanner`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BudgetPlanner`.`accounts` ;

CREATE TABLE IF NOT EXISTS `BudgetPlanner`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(319) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueUser` (`email_address` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
